### ISSUE TITLE
New Sample Request: A sample with manipulate database table

### ISSUE THREAD

**Issue by muharihar** [wso2/msf4j#123]
Hi All,

I'm very interested with WSO2 Microservices Server (WSO2 Microservice Framework for Java), It's awesome! ^_^

I'm looking for a sample with manipulate database table (CRUD), but i can't found it. Can you add a sample with manipulate mysql database table (CURD) ? I think it would help everyone.

Thanks,

**Comment by afkham** [comment]
Hi
Please take a look at the Pet microservice in the petstore sample. It is doing CRUD operations on a Redi database. It is not an RDBMS, but the concepts for an RDBMS would be the same.

https://github.com/wso2/msf4j/tree/master/samples/petstore/microservices/pet

Thanks
Azeez

**Comment by sagara-gunathunga** [comment]
You can find a very basic JPA-Hibernate sample from [here](https://github.com/wso2/msf4j/tree/master/samples/helloworld-JPA),feel free to improve this sample.
