### ISSUE TITLE
Custom ExceptionMapper for msf4j

### ISSUE THREAD

**Issue by djarkasih** [wso2/msf4j#153]
Hi guys,

First of all I would like to congrats the team for the launching of msf4j framework. Personally I think the framework is promising. Being one of the first java microservices framework based on jax-rs (or the subset) which is JEE the facto REST API standard ...

However I found out that if you send any unhandled  request to the msf4j service, the service will thrown an unhandled exception and stop working. Any subsequent request  will simply ignored/rejected. Even the one with correct URL pattern which has specific handler method assigned for it.

This could be a special case which is only happen in my case only, but nevertheless I need to create a customized exception handler that could catch this unhandled exception. Within jax-rs specification, one way to achieve that is by creating a custom ExceptionMapper class.

My questions are : 
* Does msf4j jax-rs implementation support addition of custom ExceptionMapper ?
* If it does, how can I actually incorporate my custom ExceptionMapper class into the framework ? Will the inclusion of @Produces annotation in my custom class alone enough ? 
* If it does not support custom ExceptionMapper, what is the right way to prevent unhandled exception in msf4j ?

Thanks in advanced.

Kind regards,
Ahmad R. Djarkasih.

**Comment by djarkasih** [comment]
Btw these are some part of the stack trace produce by the above incident : 
2016-03-15 15:17:40 ERROR RequestRouter:102 - Exception caught in channel processing.
org.wso2.msf4j.internal.router.HandlerException: Problem accessing: /restifier/one/two/three. Reason: Not Found

**Comment by afkham** [comment]
ExceptionMapper support has been added to the master branch.
