### ISSUE TITLE
Ember.js or or other single page application(SPA) js framework sample

### ISSUE THREAD

**Issue by ljshj** [wso2/msf4j#157]
Could you give us a sample using Ember.js or or other single page application(SPA) javascript framework ?
And use JWT for User Authentication.

**Comment by imesh** [comment]
@ljshj I assume you are asking for a JavaScript client application sample that talks to a MSF4J microservice. AFAIK we only have client application samples written Java [1], nevertheless you can implement one easily in JavaScript without much effort [2].

Regarding JWT user authentication, please refer [3].

[1] https://github.com/wso2/msf4j/tree/master/samples/
[2] http://stackoverflow.com/questions/921942/javascript-rest-client-library
[2] https://github.com/wso2/msf4j/tree/master/samples/jwt-claims
