### ISSUE TITLE
Apache benchmark command is not correct in performance test bash script

### ISSUE THREAD

**Issue by imesh** [wso2/msf4j#161]
I see the below error when perf-benchmark/run-test.sh is run:
````bash
ab -k -p 1kb_rand_data.txt -c $i -n 1000000 -H "Accept:text/plain" $service
ab: wrong number of arguments
Usage: ab [options] [http[s]://]hostname[:port]/path
````
ApacheBench Version: 2.3 Revision: 1663405

**Comment by afkham** [comment]
May be the service argument was null?

**Comment by imesh** [comment]
Yes, it was my mistake. I did not provide the service URL. May be we can add a validation in run-test.sh to detect this. Thanks!
