### ISSUE TITLE
Deploy production

### ISSUE THREAD

**Issue by odranoelBR** [wso2/msf4j#162]
Hello.
We using here WSO2 DSS and identity server.
Using WebLogic too.
I should deploy the .jar to WebLogic ? or configure .war ?

Tks

**Comment by arunasujith** [comment]
Hi @odranoelBR 

I assume that you are referring to .jar to the developed microservice?
Then you should be able to start the msf4jservice using 

java -jar NameOfJarFile.jar

You don't need a web server to deploy msf4j micro services.

Regards,
Aruna
