### ISSUE TITLE
Performance issue with MSF4J

### ISSUE THREAD

**Issue by pzfreo** [wso2/msf4j#176]
I'm not sure if this is an issue with MSF4J but I think it probably is. 

I'm running a performance test on Ubuntu 16.04. 

I'm using siege 3.1.4, with the following command line

siege -b -q -c 10 -r 10000 http://localhost:8080/purchase

I have a microservice using redis as a backend. The microservice code is available:

git clone https://github.com/pzfreo/POResourceComplete

You can simply clone / mvn clean install and then run the jar , as long as you have redis running.
mvn clean install
java -jar target/POResource-1.0.0.jar

The same code also runs under Jetty/Jersey. You can build that in the same directory with 
gradle shadowJar
java  -jar build/libs/POResourceComplete-all.jar

When I run under MSF4J I get a lot of failures.
When I run under Jetty/Jersey it works ok.

It might still be my Linux, but its highly repeatable and only happens with the MSF4J server not the Jersey server.

**Comment by pzfreo** [comment]
It seems this is fixed in 1.1.0-SNAPSHOT

Paul

**Comment by thusithathilina** [comment]
Thanks for the feedback Paul. Please let us know if you find any issues.

**Comment by afkham** [comment]
Fixed in 2.0
