### ISSUE TITLE
First time and try msf4j

### ISSUE THREAD

**Issue by magixsource** [wso2/msf4j#195]
after maven new project, msf4j gennerate Application.java and MyService.java

Run Application.java and ERROR

```
Exception in thread "main" java.lang.NoClassDefFoundError: org/wso2/carbon/kernel/transports/CarbonTransport
	at org.example.service.Application.main(Application.java:28)
Caused by: java.lang.ClassNotFoundException: org.wso2.carbon.kernel.transports.CarbonTransport
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 1 more
```

**Comment by thusithathilina** [comment]
What you mean by "after maven new project, msf4j gennerate Application.java and MyService.java" ? Did you used maven arch type to generate the project and get this error when running it?

**Comment by magixsource** [comment]
yes @thusithathilina

**Comment by thusithathilina** [comment]
@magixsource  Can you share the mvn command that you use ?

**Comment by magixsource** [comment]
```
mvn archetype:generate -DarchetypeGroupId=org.wso2.msf4j -DarchetypeArtifactId=msf4j-microservice -DarchetypeVersion=1.0.0 -DgroupId=org.example -DartifactId=Hello-Service -Dversion=1.0.0-SNAPSHOT

mvn eclipse:eclipse
```

in Eclipse:
run -org.example.service.Application.java

**Comment by thusithathilina** [comment]
@magixsource I tried your same steps and able to run the Application.java file in eclipse without any issues.
I guess you mean  -org.example.service.Application.java by right click and select run as java application in the eclipse

**Comment by magixsource** [comment]
yes, Application.java code like this:

```
public class Application {
    public static void main(String[] args) {
        new MicroservicesRunner()
                .deploy(new HelloService())
                .start();
    }
}
```
and i right click run as java application :(

**Comment by thusithathilina** [comment]
@magixsource Can you check whether you are able to access the  WSO2 Nexus repo when doing the build?

**Comment by magixsource** [comment]
@thusithathilina Could you please tell me what url WSO2 nexus repo is ?

i check my maven env, has no wso2 nexus repo mirror on maven_home/conf/setting.xml and no repo element on pom.xml .

**Comment by magixsource** [comment]
i found a url : http://maven.wso2.org/nexus/content/groups/wso2-public/ and sadly i could not access it.

**Comment by thusithathilina** [comment]
Most probably your network blocking the access to wso2 nexus repo. If possible could you try giving access to that?

**Comment by thusithathilina** [comment]
I'm closing this issue. Please do reopen if you feel still things need to be fixed.
