### ISSUE TITLE
can't run jpa module

### ISSUE THREAD

**Issue by lahirumadushanka** [wso2/msf4j#242]
i run following command "java -jar target/jpa-2.0.0-SNAPSHOT.jar" output is attached.can you help??
[run.txt](https://github.com/wso2/msf4j/files/375111/run.txt)

**Comment by thusithathilina** [comment]
@lahirumadushanka According to the error it seems you missed to add the mysql connector dependency to your project. Can you verify that?

**Comment by lahirumadushanka** [comment]
@thusithathilina thnx thilina problem was solved.
