### ISSUE TITLE
build failure spring hello world module and can't prime

### ISSUE THREAD

**Issue by lahirumadushanka** [wso2/msf4j#254]
mvn clean package
[INFO] Scanning for projects...
[INFO]
[INFO] ------------------------------------------------------------------------
[INFO] Building spring-helloworld 2.0.0-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[WARNING] The POM for org.wso2.msf4j:msf4j-spring:jar:2.0.0-SNAPSHOT is missing, no dependency information available
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 1.640 s
[INFO] Finished at: 2016-08-11T11:40:32+05:30
[INFO] Final Memory: 10M/185M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal on project spring-helloworld: Could not resolve dependencies for project org.wso2.msf4j:spring-helloworld:jar:2.0.0-SNAPSHOT: Failure to find org.wso2.msf4j:msf4j-spring:jar:2.0.0-SNAPSHOT in http://maven.wso2.org/nexus/content/repositories/releases/ was cached in the local repository, resolution will not be reattempted until the update interval of wso2.releases has elapsed or updates are forced -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/DependencyResolutionException

**Comment by thusithathilina** [comment]
You are referring to 2.0.0 snapshot, Since 2.0.0 is already release you need to change the dependency to 2.0.0

**Comment by lahirumadushanka** [comment]
sorry i couldnt understand.....

**Comment by thusithathilina** [comment]
Are you trying to build the sample from your local fork? According to the error log it seems that dependencies are still pointing to 2.0.0-SNAPSHOT version. But we have already released the 2.0.0. Therefore 2.0.0-SNAPSHOT versions are no longer available in wso2 snapshot repos. If you are using fork then you need to get a pull from the upstream(wso2 msf4j repo)
