### ISSUE TITLE
MSF4J can't handle GZIP requests

### ISSUE THREAD

**Issue by thusithathilina** [wso2/msf4j#293]
Send a GZIP request to stockquote sample. This will throw HTTP 500 error. The reason is the message that gets from carbon-transport doesn't decode the request, hence MSF4J can't process the message.

**Comment by nuwanbando** [comment]
I too get this issue, when we send a message to a msf4j service with "Content-Encoding: gzip" it fails

**Comment by daneshk** [comment]
Closing this issue. This issue is fixed with the latest transport version.
