### ISSUE TITLE
Packages not found

### ISSUE THREAD

**Issue by benhjt** [wso2/msf4j#325]
I have created a new project in eclipse based on the archetype as specified in the documentation. When this has been created I get the following errors in the `pom.xml` file:

```
Multiple annotations found at this line:
  - Missing artifact commons-io.wso2:commons-io:jar:2.4.0.wso2v1
  - Missing artifact org.wso2.carbon.transport:org.wso2.carbon.transport.http.netty:jar:2.1.2
  - Missing artifact org.wso2.carbon.messaging:org.wso2.carbon.messaging:jar:1.0.4
```
These packages are declared in the parent pom.

I have tried forcing an update of the snapshots as well as running `maven clean install` but these fail with the same errors. I have looked in the central maven repo but can't find these packages.

I am using Eclipse neon with Java 1.8.

**Comment by benhjt** [comment]
I have added the following to my `settings.xml` file in my `.m2` folder:

```
<repository>
  <id>wso2maven2</id>
  <url>https://maven.wso2.org/nexus/content/repositories/releases</url>
</repository>
```

which has resolved the artifacts but I now get:

```
Missing artifact commons-pool.wso2:commons-pool:jar:1.5.6.wso2v1
```

**Comment by thusithathilina** [comment]
@benhjt Can you please add the following repository too and tryout
https://maven.wso2.org/nexus/content/repositories/wso2-public/
The required dependecy is available in that
http://maven.wso2.org/nexus/content/groups/wso2-public/commons-pool/wso2/commons-pool/1.5.6.wso2v1/

**Comment by benhjt** [comment]
I've added the repo and now have all the dependencies required. Thanks.

**Comment by abhishar03** [comment]
Thanks it worked but , now i am getting Could not find artifact org.wso2.msf4j:msf4j-swagger:jar:2.1.1-SNAPSHOT

**Comment by thusithathilina** [comment]
@abhishar03 You are using an old snapshot version. Those snapshots are no longer available. Either you can use the 2.5.2 version or latest snapshot version which is 2.5.3-SNAPSHOT
