### ISSUE TITLE
Run Stockquote in OSGI mode

### ISSUE THREAD

**Issue by betayoga** [wso2/msf4j#326]
I'm following tutorial to run Stockquote  in osgi mode, but i get the error  Caused by: java.lang.NoClassDefFoundError: org/springframework/aop/support/AopUtils . it's look like Spring AOP not found in msf4j-core. 
[1480267703564.txt](https://github.com/wso2/msf4j/files/614855/1480267703564.txt)

error log file attached

**Comment by betayoga** [comment]
I already fix by replace jar msf4j-core_2.1.0.SNAPSHOT.jar manual on path /MSF4J-OSGI/msf4j/samples/stockquote/bundle/resources/target/wso2msf4j-2.1.0-SNAPSHOT/osgi/plugins/

**Comment by thusithathilina** [comment]
msf4j 2.1.0 is already released. You can used the released version :)
