### ISSUE TITLE
Version of dependency in branch release 2.1.0

### ISSUE THREAD

**Issue by SeraphicRav** [wso2/msf4j#331]
Hi !

The version of msf4j in at least https://github.com/wso2/msf4j/blob/release-2.1.0/samples/spring-helloworld/pom.xml is incorrect :
<dependency>
            <groupId>org.wso2.msf4j</groupId>
            <artifactId>msf4j-spring</artifactId>
            <version>2.1.1-SNAPSHOT</version>
</dependency>

It should point to version 2.1.0 I think.

Best regards

**Comment by thusithathilina** [comment]
@SeraphicRav The branch you pointed is the release-2.1.0 which was used to do the 2.1.0 release. After the release, the versions are changed to the next snapshot version.
You can see the release tag 2.1.0 and it is correctly pointing to the version
https://github.com/wso2/msf4j/blob/v2.1.0/samples/spring-helloworld/pom.xml

**Comment by SeraphicRav** [comment]
Ah ok, I was at the wrong branch, sorry and thanks !
