### ISSUE TITLE
Doesn't send a response when an interceptor returns a 'false'

### ISSUE THREAD

**Issue by rushmin** [wso2/msf4j#358]
When an interceptor returns a 'false' (e.g. in some authentication interceptor upon an authentication failure) an HTTP response is not sent. So that the client waits for a request and finally a timeout happens.

**Comment by imesh** [comment]
Thanks @rushmin for reporting this! We will investigate and get back to you soon!

**Comment by imesh** [comment]
@rushmin This is currently handled in interceptors by invoking response.send() method before executing the return statement:

```java
public abstract class AbstractBasicAuthSecurityInterceptor implements Interceptor {
    ...

    @Override
    public boolean preCall(Request request, Response responder, ServiceMethodInfo serviceMethodInfo) throws Exception {
        ...
        responder.setStatus(javax.ws.rs.core.Response.Status.UNAUTHORIZED.getStatusCode());
        responder.setHeader(javax.ws.rs.core.HttpHeaders.WWW_AUTHENTICATE, AUTH_TYPE_BASIC);
        responder.send();
        return false;
    }
    ...
}
```

We have done an improvement for this in PR https://github.com/wso2/msf4j/pull/362.

**Comment by rushmin** [comment]
Thank you @imesh . I was able to fix the issue from our side using the workaround you suggested.

**Comment by vidurananayakkara** [comment]
Closing this issue since resolved with PR https://github.com/wso2/msf4j/pull/338
