### ISSUE TITLE
Provide regex support at the class level Path annotation

### ISSUE THREAD

**Issue by thusithathilina** [wso2/msf4j#395]
There are usecases where we need to annotate service classes as follows
```java
@Path("/publisher/{version: 5.0.*})
class Publisher {
       @Path("/publish")
        public Response publishApp() {
                    ................
```
We need to check if we can provide that support

**Comment by anuruddhal** [comment]
This is already supported in current msf4j. Tested with HelloWorld sample with below regex.
```
@Path("/api/am/publisher/v1.[\\d]+/apis")
public class HelloService {
```

**Comment by thusithathilina** [comment]
Thanks for checking on this @anuruddhal Resolve this according to above comment.
