### ISSUE TITLE
Unable to use UriBuilder

### ISSUE THREAD

**Issue by trajano** [wso2/msf4j#447]
It seems that MSF4JRuntimeDelegate is taking over the UriBuilder and throwing an unsupported exception.  Is there anyway to resolve this?

**Comment by thusithathilina** [comment]
@trajano This is not supported at the moment.

**Comment by trajano** [comment]
Found a solution https://stackoverflow.com/questions/46270311/can-i-make-wso2-msf4j-work-with-jersey/46270778#46270778
