### ISSUE TITLE
Connot depoy 2 react apps when extra MSF4J bundle is added to the lib folder.

### ISSUE THREAD

**Issue by Yasara123** [wso2/msf4j#466]
When I tried deploy 2 react apps with extra MSF4J bundle , 2 react apps are not working with resource not found error.

**Comment by thusithathilina** [comment]
This happens in OSGi environment when a new service get registered (without providing a base path explicitly). Then the service list get updated at https://github.com/wso2/msf4j/blob/master/core/src/main/java/org/wso2/msf4j/internal/MicroservicesRegistryImpl.java#L80
