### ISSUE TITLE
Setting cookies in response with path and domain parameters

### ISSUE THREAD

**Issue by afarguellesd** [wso2/msf4j#468]
**Description:**
Hello.

I am developing a microservice that returns some authentication cookies. I need to set these cookies with parameters path and domain. Debugging my app show that the NewCookie var maintains the values event in the build function. Indeed the response in a Web browser or curl only shows cookie's name and value, not the domain and path values.

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**

**OS, DB, other environment details and versions:**    
* JDK 1.8.0_144
* Eclipse Neon IDE
* MVN artifact: org.wso2.msf4j.msf4j-service version 2.1.0

**Steps to reproduce:**
Create a NewCookie with all parameters and build the response: Here is a sample:
```java
NewCookie cookie = new NewCookie("test", "test", "/", ".xxxx.com.co", "Comment", 900, false, true);
ResponseBuilder builder = Response.ok();
return builder.cookie(cookie).build();
```

The output in curl is like the following:

```
curl http://localhost:8080/auth -vvv
* Hostname was NOT found in DNS cache
*   Trying 127.0.0.1...
* Connected to localhost (127.0.0.1) port 8080 (#0)
> GET /auth HTTP/1.1
> User-Agent: curl/7.35.0
> Host: localhost:8080
> Accept: */*
>
< HTTP/1.1 200 OK
< Connection: keep-alive
< Set-Cookie: test=test
< Content-Length: 0
<
* Connection #0 to host localhost left intact
```

As you see the Set-Cookie header does not contain the Path and Domain parameters.

After that I tried to set "Set-Cookie" header manually like this:

```java
return builder.header("Set-Cookie", "test=test;Path=/;Domain=.xxx.com.co").build();
```

The result in curl is this:

```
curl http://localhost:8080/auth -vvv
* Hostname was NOT found in DNS cache
*   Trying 127.0.0.1...
* Connected to localhost (127.0.0.1) port 8080 (#0)
> GET /auth HTTP/1.1
> User-Agent: curl/7.35.0
> Host: localhost:8080
> Accept: */*
>
< HTTP/1.1 200 OK
< Connection: keep-alive
< Set-Cookie: test=test;Path=/;Domain=.xxx.com.co
< Content-Length: 0
<
* Connection #0 to host localhost left intact
```
As you can see, setting the header manually there is no problem. I could use that approach but I need to set multiple "Set-Cookie" headers. 

I appreciate your help with this

**Comment by thusithathilina** [comment]
@afarguellesd I've fixed this in the master branch. Could you check with 2.4.1-SNAPSHOT version?
