### ISSUE TITLE
Websocket DeploymentTest testcase is failing with transport version upgrade

### ISSUE THREAD

**Issue by daneshk** [wso2/msf4j#496]
**Description:**
After upgrading the transport version to 6.0.51, websocket deployment is failing. This is because the way we implement websocket client in the test case is wrong with the new changes. We need to update the testcase with new changes.

**Suggested Labels:**
bug

**Suggested Assignees:**
@daneshk

**Affected Product Version:**
2.5.0

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**
Run websocket DeploymentTest testcase

**Comment by this** [comment]
Closed in #499
