### ISSUE TITLE
Update the "JWT token Sample" with the latest 5.4.0 wso2carbon.jks

### ISSUE THREAD

**Issue by jsonds** [wso2/msf4j#516]
**Description:**
The sample "JWT token Sample" fails to execute with the IS 5.4.0 pack. Please replace the .jks in [1\] the sample with the one given in the IS 5.4.0 pack.

**Refer dev mail for more details -** _Signature length not correct: got 128 but was expecting 256 when trying the JWT token Sample_

[1\] [Signature length not correct: got 128 but was expecting 256 when trying the JWT token Sample](https://github.com/wso2/msf4j/tree/master/samples/jwt-claims/sso-agent-for-jwt-webapp/src/main/resources)

**Suggested Labels:**
Improvement

**Comment by daneshk** [comment]
@jsonds Thanks for creating an issue. Is it possible to send the PR with the fix.

**Comment by jsonds** [comment]
@daneshk Sure, I will send a PR to fix this.
