### ISSUE TITLE
msf4j support for cors

### ISSUE THREAD

**Issue by shalini2789** [wso2/msf4j#552]
I created a microservice using MSF4J and tested the resources with postman all works fine but when I use it with a Angular 5 client app; the browser sends an additional http OPTIONS request to check CORS I get a "405 Method Not Allowed" Response. Can anybody help on this?

**Comment by thusithathilina** [comment]
@shalini2789 AFAIR we didn't implement CORS support. You can add OPTION support for your resource methods to get that work

**Comment by shalini2789** [comment]
Can u provide with an example as in how to implement this?
